local H = require('tests.helpers')
local surround = require('nvim-typst.surround')

describe('surround', function()
  before_each(H.need_parser)
  after_each(H.cleanup)

  describe('math', function()
    it('ds$ removes the dollars of inline math', function()
      H.buf('a $x + y$ b')
      H.cursor_at('y')
      surround.math_delete()
      T.eq('a x + y b', H.text())
    end)

    it('ds$ takes the padding of displayed math along', function()
      H.buf('a $ x + y $ b')
      H.cursor_at('y')
      surround.math_delete()
      T.eq('a x + y b', H.text())
    end)

    it('ds$ removes the lines of multi-line math', function()
      H.buf({ 'text', '$', '  x + y', '$', 'more' })
      H.cursor_at('y')
      surround.math_delete()
      T.eq({ 'text', '  x + y', 'more' }, H.lines())
    end)

    it('ts$ turns inline math into displayed math on its own lines', function()
      H.buf({ '  see $x + y$' })
      H.cursor_at('y')
      surround.math_toggle()
      T.eq({ '  see $', '    x + y', '  $' }, H.lines())
    end)

    it('ts$ turns displayed math into inline math', function()
      H.buf({ '$', '  x +', '  y', '$' })
      H.cursor_at('y')
      surround.math_toggle()
      T.eq({ '$x + y$' }, H.lines())

      H.buf('a $ x $ b')
      H.cursor_at('x')
      surround.math_toggle()
      T.eq('a $x$ b', H.text())
    end)

    it('ts$ follows edit.display_math', function()
      require('nvim-typst.config').setup({ edit = { display_math = 'display' } })
      H.buf('a $x$ b')
      H.cursor_at('x')
      surround.math_toggle()
      require('nvim-typst.config').setup({})
      T.eq('a $ x $ b', H.text())
    end)

    it('cs$ changes the layout', function()
      H.buf('a $x$ b')
      H.cursor_at('x')
      surround.math_change('d')
      T.eq('a $ x $ b', H.text())
      surround.math_change('inline')
      T.eq('a $x$ b', H.text())
    end)

    it('warns outside math', function()
      H.buf('plain text')
      surround.math_delete()
      T.ok(H.notified('not inside math'))
    end)
  end)

  describe('function calls', function()
    it('dsc unwraps a call in markup, dropping the #', function()
      H.buf('a #emph[b c] d')
      H.cursor_at('c')
      surround.cmd_delete()
      T.eq('a b c d', H.text())
    end)

    it('dsc drops the arguments of a call with a content block', function()
      H.buf('#text(red)[hot]')
      H.cursor_at('red')
      surround.cmd_delete()
      T.eq('hot', H.text())
    end)

    it('dsc unwraps the innermost call', function()
      H.buf('#strong[a #emph[b] c]')
      H.cursor_at('b')
      surround.cmd_delete()
      T.eq('#strong[a b c]', H.text())
    end)

    it('dsc keeps the content block in code', function()
      H.buf('#{ strong[x] }')
      H.cursor_at('x')
      surround.cmd_delete()
      T.eq('#{ [x] }', H.text())
    end)

    it('dsc unwraps a call in math to its arguments', function()
      H.buf('$sqrt(x + 1)$')
      H.cursor_at('x')
      surround.cmd_delete()
      T.eq('$x + 1$', H.text())
    end)

    it('dsc unwraps *strong* and _emph_', function()
      H.buf('a *b _c_* d')
      H.cursor_at('c')
      surround.cmd_delete()
      T.eq('a *b c* d', H.text())
      H.cursor_at('b')
      surround.cmd_delete()
      T.eq('a b c d', H.text())
    end)

    it('csc renames the call', function()
      H.buf('#text(red)[hot] and $sqrt(x)$')
      H.cursor_at('hot')
      surround.cmd_change('highlight')
      T.eq('#highlight(red)[hot] and $sqrt(x)$', H.text())
      H.cursor_at('x)')
      surround.cmd_change('abs')
      T.eq('#highlight(red)[hot] and $abs(x)$', H.text())
    end)

    it('csc renames a field access', function()
      H.buf('#math.equation(block: true)[x]')
      H.cursor_at('x]')
      surround.cmd_change('#box')
      T.eq('#box(block: true)[x]', H.text())
    end)

    it('csc turns *strong* into a call', function()
      H.buf('a *b* c')
      H.cursor_at('b')
      surround.cmd_change('underline')
      T.eq('a #underline[b] c', H.text())
    end)
  end)

  describe('fractions', function()
    it('tsf turns a/b into frac(a, b)', function()
      H.buf('$x + (a + 1)/2$')
      H.cursor_at('1')
      surround.toggle_fraction(false)
      T.eq('$x + frac(a + 1, 2)$', H.text())
    end)

    it('tsf turns frac(a, b) into a/b, adding parentheses as needed', function()
      H.buf('$frac(a + 1, b)$')
      H.cursor_at('b')
      surround.toggle_fraction(false)
      T.eq('$(a + 1)/b$', H.text())
    end)

    it('tsf in visual mode toggles every fraction in the selection', function()
      H.buf('$a/b + frac(c, d)$')
      vim.cmd('normal! 0v$')
      surround.toggle_fraction(true)
      T.eq('$frac(a, b) + c/d$', H.text())
    end)

    it('warns without a fraction', function()
      H.buf('$a + b$')
      H.cursor_at('a')
      surround.toggle_fraction(false)
      T.ok(H.notified('no fraction'))
    end)
  end)

  describe('delimiters', function()
    it('dsd removes brackets in math', function()
      H.buf('$2 (a + b)$')
      H.cursor_at('b')
      surround.delim_delete()
      T.eq('$2 a + b$', H.text())
    end)

    it('dsd does not break a call', function()
      H.buf('#f((1, 2))')
      H.cursor_at('2')
      surround.delim_delete()
      T.eq('#f(1, 2)', H.text())
    end)

    it('csd changes the pair', function()
      H.buf('$[a, b]$')
      H.cursor_at('b')
      surround.delim_change('<')
      T.eq('$⟨a, b⟩$', H.text())
    end)

    it('tsd wraps delimiters in lr() and unwraps them', function()
      H.buf('$(a/b)$')
      H.cursor_at('a')
      surround.delim_toggle_lr()
      T.eq('$lr((a/b))$', H.text())
      H.cursor_at('a')
      surround.delim_toggle_lr()
      T.eq('$(a/b)$', H.text())
    end)
  end)

  describe('<F7>', function()
    -- The insert-mode tests put the cursor past the end of the line.
    before_each(function()
      vim.o.virtualedit = 'onemore'
    end)
    after_each(function()
      vim.o.virtualedit = ''
    end)

    it('wraps the word in markup in #name[…]', function()
      H.buf('a word b')
      H.cursor_at('or')
      surround.cmd_create(false, 'emph')
      T.eq('a #emph[word] b', H.text())
    end)

    it('wraps the word in math in name(…)', function()
      H.buf('$a + x$')
      H.cursor_at('x')
      surround.cmd_create(false, 'bold')
      T.eq('$a + bold(x)$', H.text())
    end)

    it('wraps the visual selection', function()
      H.buf('one two three')
      H.cursor_at('two')
      vim.cmd('normal! vee')
      surround.cmd_create(true, 'strong')
      T.eq('one #strong[two three]', H.text())
    end)

    it('turns the word before the cursor into a call in insert mode', function()
      H.buf('a emph')
      H.cursor(1, 6)
      surround.cmd_create_insert()
      T.eq('a #emph[]', H.text())
      T.eq({ 1, 8 }, vim.api.nvim_win_get_cursor(0))

      H.buf('$sqrt$')
      H.cursor(1, 5)
      surround.cmd_create_insert()
      T.eq('$sqrt()$', H.text())
      T.eq({ 1, 6 }, vim.api.nvim_win_get_cursor(0))
    end)
  end)

  describe(']] in insert mode', function()
    before_each(function()
      vim.o.virtualedit = 'onemore'
    end)
    after_each(function()
      vim.o.virtualedit = ''
    end)

    local function open(text)
      return vim.tbl_map(function(entry)
        return entry.char
      end, surround.open_delims(text))
    end

    it('tracks brackets of embedded code and math', function()
      T.eq({ '[', '$', '(' }, open('#strong[a $f(x'))
      T.eq({ '(', '(' }, open('#text(red, size: (1pt'))
      T.eq({}, open('#strong[a] $x$'))
      T.eq({ '[' }, open('#text(red)[a'))
      T.eq({ '[', '{', '[' }, open('#box[y](z) #[#{ let x = ['))
    end)

    it('ignores prose, strings, raw text, comments and escapes', function()
      T.eq({}, open('see (above [here'))
      T.eq({ '(' }, open('#f("(", `)`, \n// )\n'))
      T.eq({ '$' }, open('\\$ $x /* $ */'))
      T.eq({}, open('```\n(\n'))
    end)

    it('inserts the closer at the cursor', function()
      H.buf('#emph[$ f(x')
      H.cursor(1, 11)
      surround.delim_close()
      T.eq('#emph[$ f(x)', H.text())
      T.eq({ 1, 12 }, vim.api.nvim_win_get_cursor(0))
      surround.delim_close()
      T.eq('#emph[$ f(x) $', H.text())
      surround.delim_close()
      T.eq('#emph[$ f(x) $]', H.text())
    end)
  end)
end)
