#!/usr/bin/env python3
"""Generate lua/nvim-typst/conceal/symbols.lua from the installed `typst`.

Run from the repository root after a Typst release changes the `sym` module:

    python3 scripts/gen_symbols.py

`greek` and `math` come from `typst eval` over `sym`, `fonts` from the Unicode
character names, and `superscript`/`subscript` are the tables below, the same
as nvim-tex's.
"""
import json, re, subprocess, sys, unicodedata

out_path = sys.argv[1] if len(sys.argv) > 1 else 'lua/nvim-typst/conceal/symbols.lua'
version = subprocess.check_output(['typst', '--version'], text=True).strip()
pairs = json.loads(subprocess.check_output(['typst', 'eval',
    'dictionary(sym).pairs().filter(p => type(p.at(1)) == symbol).map(p => (p.at(0), repr(p.at(1))))'], text=True))

STR = r'"((?:[^"\\]|\\.)*)"'
def unesc(s):
    s = re.sub(r'\\u\{([0-9a-fA-F]+)\}', lambda m: chr(int(m.group(1), 16)), s)
    return re.sub(r'\\(.)', r'\1', s)

flat = {}
for name, r in pairs:
    body = r[len('symbol('):-1]
    for m in re.finditer(r'\(\s*' + STR + r'\s*,\s*' + STR + r'\s*\)|^\s*' + STR, body, re.M):
        if m.group(3) is not None:
            flat[name] = unesc(m.group(3))
        else:
            flat[name + '.' + m.group(1)] = unesc(m.group(2))

def usable(v):
    v = v.replace('\ufe0e', '').replace('\ufe0f', '')
    if len(v) != 1:
        return None
    if unicodedata.category(v) in ('Zs', 'Zl', 'Zp', 'Cc', 'Cf', 'Mn', 'Me', 'Co', 'Cn'):
        return None
    return v

greek, math = {}, {}
for k, v in flat.items():
    v = usable(v)
    if not v:
        continue
    (greek if 0x370 <= ord(v) <= 0x3FF else math)[k] = v

def lua_str(s):
    if "'" in s:
        return '"' + s.replace('\\', '\\\\').replace('"', '\\"') + '"'
    return "'" + s.replace('\\', '\\\\') + "'"

# Math alphanumerics, by the Unicode character names. Letterlike symbols
# (ℝ, ℬ, ℭ, ...) fill the holes of the Mathematical Alphanumeric block.
LETTERLIKE = {'DOUBLE-STRUCK': 'DOUBLE-STRUCK', 'SCRIPT': 'SCRIPT', 'FRAKTUR': 'BLACK-LETTER'}
def font(style, digits):
    table = {}
    chars = [chr(c) for c in range(ord('A'), ord('Z') + 1)] + [chr(c) for c in range(ord('a'), ord('z') + 1)]
    for ch in chars:
        case = 'CAPITAL' if ch.isupper() else 'SMALL'
        for n in ('MATHEMATICAL %s %s %s' % (style, case, ch.upper()),
                  '%s %s %s' % (LETTERLIKE.get(style, '-'), case, ch.upper())):
            try:
                table[ch] = unicodedata.lookup(n)
                break
            except KeyError:
                pass
    if digits:
        for i, d in enumerate(['ZERO', 'ONE', 'TWO', 'THREE', 'FOUR', 'FIVE', 'SIX', 'SEVEN', 'EIGHT', 'NINE']):
            try:
                table[str(i)] = unicodedata.lookup('MATHEMATICAL %s DIGIT %s' % (style, d))
            except KeyError:
                pass
    return table

fonts = {
    'bb': font('DOUBLE-STRUCK', True),
    'cal': font('SCRIPT', False),
    'scr': font('SCRIPT', False),
    'frak': font('FRAKTUR', False),
    'bold': font('BOLD', True),
    'sans': font('SANS-SERIF', True),
    'mono': font('MONOSPACE', True),
}

# The characters Unicode has a super- or subscript form of, limited to the
# Basic Multilingual Plane.
SUPERSCRIPT = {
    "(": "⁽", ")": "⁾", "+": "⁺", "-": "⁻", "0": "⁰", "1": "¹", "2": "²", "3": "³", "4": "⁴",
    "5": "⁵", "6": "⁶", "7": "⁷", "8": "⁸", "9": "⁹", "=": "⁼", "A": "ᴬ", "B": "ᴮ", "C": "ꟲ",
    "D": "ᴰ", "E": "ᴱ", "F": "ꟳ", "G": "ᴳ", "H": "ᴴ", "I": "ᴵ", "J": "ᴶ", "K": "ᴷ", "L": "ᴸ",
    "M": "ᴹ", "N": "ᴺ", "O": "ᴼ", "P": "ᴾ", "Q": "ꟴ", "R": "ᴿ", "T": "ᵀ", "U": "ᵁ", "V": "ⱽ",
    "W": "ᵂ", "a": "ᵃ", "b": "ᵇ", "c": "ᶜ", "d": "ᵈ", "e": "ᵉ", "f": "ᶠ", "g": "ᵍ", "h": "ʰ",
    "i": "ⁱ", "j": "ʲ", "k": "ᵏ", "l": "ˡ", "m": "ᵐ", "n": "ⁿ", "o": "ᵒ", "p": "ᵖ", "r": "ʳ",
    "s": "ˢ", "t": "ᵗ", "u": "ᵘ", "v": "ᵛ", "w": "ʷ", "x": "ˣ", "y": "ʸ", "z": "ᶻ",
}
SUBSCRIPT = {
    "(": "₍", ")": "₎", "+": "₊", "-": "₋", "0": "₀", "1": "₁", "2": "₂", "3": "₃", "4": "₄",
    "5": "₅", "6": "₆", "7": "₇", "8": "₈", "9": "₉", "=": "₌", "a": "ₐ", "e": "ₑ", "h": "ₕ",
    "i": "ᵢ", "j": "ⱼ", "k": "ₖ", "l": "ₗ", "m": "ₘ", "n": "ₙ", "o": "ₒ", "p": "ₚ", "r": "ᵣ",
    "s": "ₛ", "t": "ₜ", "u": "ᵤ", "v": "ᵥ", "x": "ₓ",
}

L = []
w = L.append
w('--- Replacement characters for `nvim-typst.conceal`.')
w('---')
w('--- GENERATED by scripts/gen_symbols.py -- do not edit by hand.')
w('---')
w("--- `greek` and `math` are every variant of Typst's `sym` module")
w('--- (%s) that is a single visible character; `fonts` comes' % version)
w('--- from the Unicode character names; `superscript` and `subscript` are the')
w('--- characters Unicode has, limited to the Basic Multilingual Plane, which is')
w('--- what fonts reliably cover.')
w('')
w('return {')
def dump(name, doc, table, indent='  '):
    w(indent + '--- ' + doc)
    w(indent + name + ' = {')
    for k in sorted(table):
        w(indent + '  [%s] = %s,' % (lua_str(k), lua_str(table[k])))
    w(indent + '},')
dump('greek', 'Greek letters: `alpha`, `phi.alt`, `Omega`.', greek)
dump('math', 'Every other symbol: `arrow.r`, `RR`, `subset.eq`, `infinity`.', math)
w('  --- `bb(R)` and friends, keyed by the function, then by the letter.')
w('  fonts = {')
for f in sorted(fonts):
    w('    ' + f + ' = {')
    for k in sorted(fonts[f]):
        w('      [%s] = %s,' % (lua_str(k), lua_str(fonts[f][k])))
    w('    },')
w('  },')
dump('superscript', '`x^2`, `x^(n+1)`, per character.', SUPERSCRIPT)
dump('subscript', '`x_1`, `x_(i+1)`, per character.', SUBSCRIPT)
w('}')
open(out_path, 'w').write('\n'.join(L) + '\n')
print(len(greek), len(math), {k: len(v) for k, v in fonts.items()})
